version: '3.9'

services:
  db:
    image: postgres:14
    container_name: community-core-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community-core
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: community-core-adminer
    ports:
      - '8080:8080'

volumes:
  db_data:
