version: "3.9"

services:
  api:
    image: ghcr.io/yosuahalim/community-core-api:latest
    build: .
    container_name: community-core-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"

  db:
    image: postgres:14
    container_name: community-core-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community-core
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
