version: "3.9"

services:
  api:
    image: ghcr.io/legacy-sukawarna/community-core-api:latest
    build: .
    container_name: community-core-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.community-api.rule=Host(`community-api.srv1208734.hstgr.cloud`)"
      - "traefik.http.routers.community-api.entrypoints=websecure"
      - "traefik.http.routers.community-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.community-api.loadbalancer.server.port=3000"

  db:
    image: postgres:14
    container_name: community-core-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community-core
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  n8n_default:
    external: true

volumes:
  db_data:
